name: lint and test
on: [push]
jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make build
          make install
          make package-install
      - name: Run linter and pytest
        run: |
          make lint
          make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
      